version: '3.3'

volumes:
  docs:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data/

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - ./backend/data:/app/data/
      - static:/backend_static/
      - media:/media/
      - docs:/docs/
    depends_on:
      - db

  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/result_build/. /static/
    volumes:
      - static:/frontend_static/
      - docs:/docs/

  nginx:
    build: ./infra/
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - static:/staticfiles/
      - media:/mediafiles/
      - docs:/docfiles/
    depends_on:
      - backend
      - frontend
