# Generated by Django 3.2.16 on 2024-09-07 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное значение поля - 1.'), django.core.validators.MaxValueValidator(5000, message='Максимальное значение поля - 5000.')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Минимальное значение поля - 1.'), django.core.validators.MaxValueValidator(10000, message='Максимальное значение поля - 10000.')], verbose_name='Время приготовления'),
        ),
    ]
