# Generated by Django 3.2.16 on 2024-09-08 10:31

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_follow_user_and_following_are_different'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_and_following_are_different',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(('user', django.db.models.expressions.F('following')), _negated=True), name='user_and_following_are_different'),
        ),
    ]
