# Generated by Django 3.2.16 on 2024-09-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20240908_1331'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
