# Generated by Django 3.2.16 on 2024-09-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_delete_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='short_url',
        ),
    ]
