# Generated by Django 3.2.16 on 2024-09-08 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_recipe_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='short_url',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Короткий URL'),
        ),
    ]
